packages: []
verifyDepsBeforeRun: false
onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
allowBuilds:
  '@firebase/util': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
